global:
  scrape_interval:     5s
  evaluation_interval: 5s 

scrape_configs: 
  - job_name: 'feedbackscollector'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'feedbackscollector:8080' ]
  - job_name: 'feedbacksstorage'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'feedbacksstorage:9010' ]
  - job_name: 'feedbacksanalysis'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'feedbacksanalysis:8081' ]
  - job_name: 'gatewayserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'gatewayserver:8072' ]
  - job_name: 'eurekaserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'eurekaserver:8070' ]

