server:
  port: 9010

spring:
  application:
    name: "feedbacksstorage"
  data:
    mongodb:
      host: localhost
      port: 27017
      database: feedback-restaurant
  cloud:
    function:
      definition: feedbacksReceiver;analysisByRegion;requestAnalysisByAgeGroup
    stream:
      bindings:
        feedbacksReceiver-in-0:
          destination: send-feedback
          group: ${spring.application.name}
        analysisByRegion-in-0:
          destination: request-analysis-by-region
          group: ${spring.application.name}
        requestAnalysisByAgeGroup-in-0:
          destination: request-analysis-by-age-group
          group: ${spring.application.name}
        analysisByRegion-out-0:
          destination: receive-analysis-by-region
        requestAnalysisByAgeGroup-out-0:
          destination: receive-analysis-age-group
      kafka:
        binder:
          brokers:
            - localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
endpoints:
  shutdown:
    enabled: true


info:
  app:
    name: "feedbacksstorage"
    description: "Restaurant Franchise Feedbacks Analysis Application"
    version: "1.0.0"

logging:
  level:
    com:
      restaurant:
        feedbacksstorage: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"


