server:
  port: 8081

spring:
  application:
    name: "feedbacksanalysis"
  cloud:
    function:
      definition: receiveAnalysisByRegion;receiveAnalysisAgeGroup;requestCustomAnalysis
    stream:
      bindings:
        receiveAnalysisByRegion-in-0:
          destination: receive-analysis-by-region
          group: ${spring.application.name}
        receiveAnalysisAgeGroup-in-0:
          destination: receive-analysis-age-group
        requestCustomAnalysis-in-0:
          destination: receive-custom-analysis
          group: ${spring.application.name}
        requestAnalysisByRegion-out-0:
          destination: request-analysis-by-region
        requestAnalysisByAgeGroup-out-0:
          destination: request-analysis-by-age-group
        requestCustomAnalysis-out-0:
          destination: request-custom-analysis
      kafka:
        binder:
          brokers:
            - localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "feedbacksanalysis"
    description: "Restaurant Franchise Feedbacks Analysis Application"
    version: "1.0.0"

logging:
  level:
    com:
      restaurant:
        feedbacksanalysis: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
